### PR TITLE
Update PosePlugin to 1.17.1

### LINKED ISSUE #5: [BUG] command /stand not work
**Describe the bug**
`/stand` not work

**To Reproduce**
1. Type `/stand`

**Expected behavior**
`/stand` should not exist

**Plugin version:**
poseplugin-experimental-4.0-beta-1

**Console log**
```[12:45:52 INFO]: Disguys issued server command: /stand
[12:45:52 WARN]: java.lang.NoSuchMethodException: ru.armagidon.poseplugin.api.poses.AbstractPose$1.<init>(org.bukkit.entity.Player)
[12:45:52 WARN]: at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[12:45:52 WARN]: at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2691)
[12:45:52 WARN]: at ru.armagidon.poseplugin.api.poses.PoseBuilder.build(PoseBuilder.java:40)
[12:45:52 WARN]: at ru.armagidon.poseplugin.plugin.commands.PoseCommandGenerator.lambda$generatePoseCommands$4(PoseCommandGenerator.java:63)
[12:45:52 WARN]: at ru.armagidon.poseplugin.plugin.commands.SimpleCommand.lambda$new$1(SimpleCommand.java:39)
[12:45:52 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:45:52 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:45:52 WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[12:45:52 WARN]: at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2263)
[12:45:52 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2074)
[12:45:52 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2055)
[12:45:52 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:45:52 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:45:52 WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:45:52 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:45:52 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:45:52 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:45:52 WARN]: at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1399)
[12:45:52 WARN]: at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[12:45:52 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:45:52 WARN]: at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1377)
[12:45:52 WARN]: at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1370)
[12:45:52 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[12:45:52 WARN]: at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1346)
[12:45:52 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1257)
[12:45:52 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[12:45:52 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)```

### LINKED ISSUE #7: [BUG] Pose /lay and others not working on MC 1.17.1
**Describe the bug**
command `/lay` warnings

**To Reproduce**
1. Send `/lay`

**Plugin version:**
PosePlugin-4.0-Beta-1

**Server software**
Airplane 1.17.1 build 45

**Console log**
```
[Mon, 12. Jul 2021 12:59:33 UTC INFO] LinKs_QQ issued server command: /lay
[Mon, 12. Jul 2021 12:59:33 UTC WARN] java.lang.reflect.InvocationTargetException
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.api.poses.PoseBuilder.build(PoseBuilder.java:40)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.plugin.commands.PoseCommandGenerator.lambda$generatePoseCommands$4(PoseCommandGenerator.java:63)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.plugin.commands.SimpleCommand.lambda$new$1(SimpleCommand.java:39)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2243)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2035)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.TickTask.run(TickTask.java:18)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1407)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1385)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1378)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1354)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1265)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/java.lang.Thread.run(Thread.java:831)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] Caused by: java.lang.reflect.InvocationTargetException
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.api.utils.nms.ToolFactory.create(ToolFactory.java:71)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.api.poses.seatrequiring.LayPose.<init>(LayPose.java:23)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] ... 30 more
[Mon, 12. Jul 2021 12:59:33 UTC WARN] Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)'
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.api.utils.nms.v1_17.npc.FakePlayer117.<init>(FakePlayer117.java:122)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] ... 37 more
```

### PR DESCRIPTION
**Pull request by fgRuslan**
Fixes #7 Fixes #5

### CODE REVIEW

**Comment by armagidon-exception** [comment]
Did you test those?

**Comment by fgRuslan** [comment]
The only ones I didn't test are the ones that are brought by a resource pack

**Comment by armagidon-exception** [comment]
I mean test plugin with these changes.

**Comment by fgRuslan** [comment]
I tested it and it works. These screenshots will prove you that it works

**Pull request merged**
